name: ShellCheck

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.sh'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          path: main

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
